name: Build Suggestion
description: Submit a build suggestion.
title: "[Build]: "
labels: ["hardware", "build"]
assignees:
  - haydenbspence
body:
  - type: dropdown
    id: build-type
    attributes:
      label: Type of Build
      description: What type of build is this?
      options:
        - Inference Only
        - Inference & Training
      default: 0
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Build Source
      description: If there is a link that describes the build, please provide it here.
      placeholder: https://archive.is/
    validations:
      required: false
  - type: textarea
    id: build
    attributes:
      label: Build Description
      value: "Describe the build."
    validations:
      required: true

